INSERT IGNORE INTO sys_permission (name, code, type, parent_id, sort)
VALUES
    ('新增部门', 'department:create', 'ACTION', 0, 1000),
    ('编辑部门', 'department:update', 'ACTION', 0, 1010),
    ('删除部门', 'department:delete', 'ACTION', 0, 1020),
    ('新增用户', 'user:create', 'ACTION', 0, 1030),
    ('编辑用户', 'user:update', 'ACTION', 0, 1040),
    ('删除用户', 'user:delete', 'ACTION', 0, 1050),
    ('新增角色分组', 'role-group:create', 'ACTION', 0, 1060),
    ('编辑角色分组', 'role-group:update', 'ACTION', 0, 1070),
    ('删除角色分组', 'role-group:delete', 'ACTION', 0, 1080),
    ('分配权限', 'permission:assign', 'ACTION', 0, 1090),
    ('新增需求', 'requirement:create', 'ACTION', 0, 1100),
    ('编辑需求', 'requirement:update', 'ACTION', 0, 1110),
    ('删除需求', 'requirement:delete', 'ACTION', 0, 1120),
    ('指派需求', 'requirement:assign', 'ACTION', 0, 1130),
    ('新增Bug', 'bug:create', 'ACTION', 0, 1140),
    ('编辑Bug', 'bug:update', 'ACTION', 0, 1150),
    ('删除Bug', 'bug:delete', 'ACTION', 0, 1160),
    ('指派Bug', 'bug:assign', 'ACTION', 0, 1170);
